# Test
GET http://localhost:8081/test HTTP/1.1

###
# Ping Databases
GET http://localhost:8081/ping HTTP/1.1

###
# Unlock Databases
GET http://localhost:8081/unlock HTTP/1.1

###
# Get Reports
GET http://localhost:8081/reports HTTP/1.1

###
# Get all appointments
GET http://localhost:8081/appointments HTTP/1.1

###
# Search appointments by filter
POST http://localhost:8081/appointments/search HTTP/1.1
content-type: application/json

{
    "patient_name": "t",
    "appointment_status": "Queued"
}

###
# Get Luzon appointment by ID
GET http://localhost:8081/appointments/1 HTTP/1.1

###
# Get VisMin appointment by ID
GET http://localhost:8081/appointments/2 HTTP/1.1

###
# Create new Luzon appointment
POST http://localhost:8081/appointments HTTP/1.1
content-type: application/json

{
    "patient_name": "test",
    "patient_age": "69",
    "doctor_name": "test",
    "doctor_specialty": "test",
    "clinic_name": "test",
    "clinic_city": "test",
    "island_group": "Luzon",
    "appointment_date": "2024-04-07",
    "appointment_status": "Queued"
}

###
# Create new Visayas appointment
POST http://localhost:8081/appointments HTTP/1.1
content-type: application/json

{
    "patient_name": "test",
    "patient_age": "69",
    "doctor_name": "test",
    "doctor_specialty": "test",
    "clinic_name": "test",
    "clinic_city": "test",
    "island_group": "Visayas",
    "appointment_date": "2024-04-07",
    "appointment_status": "Queued"
}

###
# Update Luzon appointment
PATCH http://localhost:8081/appointments/35 HTTP/1.1
content-type: application/json

{
    "patient_name": "test",
    "patient_age": 269,
    "doctor_name": "test",
    "doctor_specialty": "test",
    "clinic_name": "test",
    "clinic_city": "test",
    "island_group": "Luzon",
    "appointment_date": "2024-04-06T16:00:00.000Z",
    "appointment_status": "Queued",
    "time_queued": "2024-04-08 10:26:00.000"
}

###
# Update Visayas appointment
PATCH http://localhost:8081/appointments/68 HTTP/1.1
content-type: application/json

{
    "patient_name": "test",
    "patient_age": 269,
    "doctor_name": "test",
    "doctor_specialty": "test",
    "clinic_name": "test",
    "clinic_city": "test",
    "island_group": "Visayas",
    "appointment_date": "2024-04-06T16:00:00.000Z",
    "appointment_status": "Queued",
    "time_queued": "2024-04-08 10:26:00.000"
}

###
# Delete Luzon appointment
DELETE http://localhost:8081/appointments/53 HTTP/1.1
content-type: application/json

###
# Delete Visayas appointment
DELETE http://localhost:8081/appointments/74 HTTP/1.1